"""empty message

Revision ID: dbb14e99d8d1
Revises: 91aa4118dfcb
Create Date: 2019-02-14 00:29:41.371331

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = 'dbb14e99d8d1'
down_revision = '91aa4118dfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_account', sa.Column('username', sa.String(length=120), nullable=False, server_default=str(uuid.uuid4())))
    op.create_unique_constraint(None, 'personal_account', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_account', type_='unique')
    op.drop_column('personal_account', 'username')
    # ### end Alembic commands ###
